Disable harbour temporarily

diff --git a/.github/workflows/kernel_push.yaml b/.github/workflows/kernel_push.yaml
--- a/.github/workflows/kernel_push.yaml
+++ b/.github/workflows/kernel_push.yaml
@@ -26,11 +26,11 @@ jobs:
       matrix:
         kernel: ${{ fromJSON(needs.discover-kernels.outputs.kernels) }}
     steps:
-      - name: Debug connectivity to Harbor
-        run: |
-          echo "Testing Harbor from inside GitHub Actions..."
-          getent hosts harbor.cloud.infn.it || nslookup harbor.cloud.infn.it || true
-          curl -vkI --connect-timeout 10 https://harbor.cloud.infn.it/ || echo "curl failed"
+      #- name: Debug connectivity to Harbor
+      #  run: |
+      #    echo "Testing Harbor from inside GitHub Actions..."
+      #    getent hosts harbor.cloud.infn.it || nslookup harbor.cloud.infn.it || true
+      #    curl -vkI --connect-timeout 10 https://harbor.cloud.infn.it/ || echo "curl failed"
 
       - name: Checkout
         uses: actions/checkout@v2
@@ -44,12 +44,12 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
 
-      - name: Login to INFN Container Registry
-        uses: docker/login-action@v3
-        with:
-          registry: harbor.cloud.infn.it
-          username: ${{ secrets.HARBOR_USER }}
-          password: ${{ secrets.HARBOR_CLISECRET }}
+      #- name: Login to INFN Container Registry
+      #  uses: docker/login-action@v3
+      #  with:
+      #    registry: harbor.cloud.infn.it
+      #    username: ${{ secrets.HARBOR_USER }}
+      #    password: ${{ secrets.HARBOR_CLISECRET }}
 
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v3
@@ -68,8 +68,6 @@ jobs:
           context: ./${{ matrix.kernel }}/
           outputs: "type=registry,push=true"
           tags: |
-            harbor.cloud.infn.it/unpacked/betif_difaet/${{ matrix.kernel }}:${{ env.RELEASE_VERSION }}
-            harbor.cloud.infn.it/unpacked/betif_difaet/${{ matrix.kernel }}:latest
             ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/${{ matrix.kernel }}:${{ env.RELEASE_VERSION }}
             ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/${{ matrix.kernel }}:latest
           file: ./${{ matrix.kernel }}/Dockerfile
